In [6]:
import numpy as np
#Crea una matriz bidimensional llamada "matriz3x3"
matriz_3x3 = np.arange(9).reshape(3,3)
print(matriz_3x3)
#Crear una matriz identidad de 6x6
matriz_identidad = np.identity(6)
print(matriz_identidad)

StatementMeta(SPK00, 27, 7, Finished, Available)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
